### ISSUE TITLE
admin permission required

### ISSUE THREAD

**Issue by jonschadt** [InnoSpectra/ISC-NIRScan-GUI#1]
the GUI application requires admin rights to launch on windows 10, is there a way to allow standard users to run the application?

**Comment by JeremyHsieh** [comment]
You can find the GUI application requires no admin rights in the release page which file name contains "NoUAC".
https://github.com/InnoSpectra/ISC-NIRScan-GUI/releases

**Comment by jonschadt** [comment]
this worked perfect thankyou
